version: "4.8"  # Adjust the version if necessary

services:
  nginx:
    image: eazibotsnginx:latest
    container_name: "my_nginx"
    ports:
      - 80:80
      - 443:443
    depends_on:
      - django

  django:
    image: ${DOCKER_USERNAME}/eazibots:latest
    container_name: "my_django"
    ports:
      - "8080:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - TEST_STRIPE_KEY=${TEST_STRIPE_KEY}
      - REDIS_BIND_IP=0.0.0.0
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - DOCKER_USERNAME=${DOCKER_USERNAME}
      - DOCKER_PASSWORD=${DOCKER_PASSWORD}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
    command: >
      bash -c "python manage.py migrate &&  python manage.py runserver 0.0.0.0:8080"
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: "my_redis"
    ports:
      - 6379:6379
    command: redis-server --bind 0.0.0.0 --requirepass ${REDIS_PASSWORD} --port 6379
    depends_on:
      - postgres
                    
  postgres:
    image: postgres:latest
    container_name: "my_postgres"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
